// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Xenaia.Data;

#nullable disable

namespace Xenaia.Data.PostgreSql.Migrations
{
    [DbContext(typeof(XenaiaDbContext))]
    [Migration("20260717060703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Xenaia.Core.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL AND error IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLanguage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("activity_language");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("ChannelBookingCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("channel_booking_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CreatedAtExternal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_external");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_price");

                    b.Property<string>("LeadContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lead_contact_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone");

                    b.Property<string>("Referrer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("referrer");

                    b.Property<string>("SecretCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("UpdatedAtExternal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_external");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sync", "Xenaia.Domain.Bookings.Bookings.Booking.Sync#SyncState", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Error")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("sync_error");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("sync_status");

                            b1.Property<DateTimeOffset?>("SyncedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("synced_at");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_code");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_at");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<int>("ExternalOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("external_option_id");

                    b.Property<string>("ExtraAlias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("extra_alias");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_booking_extra");

                    b.HasIndex("BookingId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_extra_booking_id_external_id");

                    b.ToTable("booking_extra", (string)null);
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingGiftCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_booking_gift_card");

                    b.HasIndex("BookingId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_gift_card_booking_id_code");

                    b.ToTable("booking_gift_card", (string)null);
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_at");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<bool>("CheckedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("checked_in");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<int>("ExternalOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("external_option_id");

                    b.Property<int>("ExternalProductId")
                        .HasColumnType("integer")
                        .HasColumnName("external_product_id");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_price");

                    b.Property<string>("ParticipantTypeAlias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("participant_type_alias");

                    b.HasKey("Id")
                        .HasName("pk_booking_item");

                    b.HasIndex("BookingId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_item_booking_id_external_id");

                    b.ToTable("booking_item", (string)null);
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_booking_payment");

                    b.HasIndex("BookingId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_payment_booking_id_external_id");

                    b.ToTable("booking_payment", (string)null);
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingExtra", b =>
                {
                    b.HasOne("Xenaia.Domain.Bookings.Bookings.Booking", null)
                        .WithMany("Extras")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_booking_extra_bookings_booking_id");
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingGiftCard", b =>
                {
                    b.HasOne("Xenaia.Domain.Bookings.Bookings.Booking", null)
                        .WithMany("GiftCards")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_booking_gift_card_bookings_booking_id");
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingItem", b =>
                {
                    b.HasOne("Xenaia.Domain.Bookings.Bookings.Booking", null)
                        .WithMany("Items")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_booking_item_bookings_booking_id");
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.BookingPayment", b =>
                {
                    b.HasOne("Xenaia.Domain.Bookings.Bookings.Booking", null)
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_booking_payment_bookings_booking_id");
                });

            modelBuilder.Entity("Xenaia.Domain.Bookings.Bookings.Booking", b =>
                {
                    b.Navigation("Extras");

                    b.Navigation("GiftCards");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
